// Module included in the following assemblies:
// Epic CNF-2600 (CNF-2133) (4.10), Story TELCODOCS-285
// * scalability_and_performance/cnf-talo-for-cluster-upgrades.adoc

:_content-type: PROCEDURE
[id="talo-create-cgu-cr_{context}"]
= Creating the ClusterGroupUpgrade CR

You can control cluster updates with the `ClusterGroupUpgrade` CRs. 

.Prerequisites

* Install the Topology Aware Lifecycle Operator.
* Provision one or more managed clusters.
* Log in as a user with `cluster-admin` privileges.
* Create RHACM policies in the Hub cluster.

.Procedure

. Save the following YAML file in the `cgu-upgrade.yaml` file.
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-upgrade-complete
  namespace: default
spec:
  clusters:
  - spoke1
  enable: false <1>
  managedPolicies:
  - policy1-common-cluster-version-policy
  - policy2-common-pao-sub-policy
  remediationStrategy:
    maxConcurrency: 1
    timeout: 240
----
<1> The update process does not start until the `spec.enable` field is set to `true`.

. Create the `ClusterGroupUpgrade` CR by running the following command:
+
[source,terminal]
----
$ oc create -f cgu-upgrade.yaml
----

.Verification

. Check if the `ClusterGroupUpgrade` CR exists in the Hub cluster by running the following command:
+
[source,terminal]
----
$ oc get cgu -A
----
+
.Example output
+
[source,terminal]
----
NAMESPACE       NAME                   AGE
default         cgu-upgrade-complete   5s
----