// Module included in the following assemblies:
// Epic CNF-2600 (CNF-2133) (4.10), Story TELCODOCS-285
// * scalability_and_performance/ztp-deploying-disconnected.adoc

:_content-type: PROCEDURE
[id="talo-platform-update_{context}"]
= Performing a platform update

.Prerequisites

* Install the Topology Aware Lifecycle Operator.
* Update ZTP to the latest version. 
* Provision one or more managed clusters with ZTP.
* Mirror the desired image repository.
* Log in as a user with `cluster-admin` privileges.
* Create {rh-rhacm} policies in the Hub cluster.

.Procedure

. Create a `PolicyGenTemplate` CR for the platform update:
.. Save the following contents of the `PolicyGenTemplate` CR in the `du-upgrade.yaml` file.
+
.Example of `PolicyGenTemplate` for platform update 
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1
kind: PolicyGenTemplate
metadata:
  name: "du-upgrade"
  namespace: "ztp-group-du-sno"
spec:
  bindingRules:
    group-du-sno: ""
  mcp: "master"
  remediationAction: inform
  sourceFiles: 
    - fileName: ImageSignature.yaml <1>
      policyName: "platform-upgrade-prep"
      binaryData:
        ${DIGEST_ALGO}-${DIGEST_ENCODED}: ${SIGNATRUE_BASE64} <2>
    - fileName: DisconnectedICSP.yaml
      policyName: "platform-upgrade-prep"
      metadata:
        name: disconnected-internal-icsp-for-ocp
      spec:
        repositoryDigestMirrors: <3>
          - mirrors:
            - quay-intern.example.com/ocp4/openshift-release-dev
            source: quay.io/openshift-release-dev/ocp-release
          - mirrors:
            - quay-intern.example.com/ocp4/openshift-release-dev
            source: quay.io/openshift-release-dev/ocp-v4.0-art-dev <4>
    - fileName: ClusterVersion.yaml <5>
      policyName: "platform-upgrade-prep"
      metadata:
        name: version
      spec:
        upstream: http://upgrade.example.com/images/upgrade-graph_stable-4.10
    - fileName: ClusterVersion.yaml <6>
      policyName: "platform-upgrade"
      metadata:
        name: version
      spec:
        channel: "stable-4.10"
        upstream: http://upgrade.example.com/images/upgrade-graph_stable-4.10
        desiredUpdate:
          version: 4.10.4
      status:
        history:
          - version: 4.10.4
            state: "Completed"
----
<1> The `ConfigMap` CR contains the signature of the desired release image to update to.
<2> Shows the image signature of the desired {product-title} release. If you followed the steps in "Mirroring the OpenShift Container Platform image repository" section, you can get the image signature at `${REMOVABLE_MEDIA_PATH}/mirror/config/<image_signature_file>`.
<3> Shows the mirror repository that contains the desired {product-title} image.
<4> Shows the source repository that the desired {product-title} image is pulled from. You can list the required mirror registries by running the `oc adm release mirror` command.
<5> Shows the `ClusterVersion` CR to update upstream.
<6> Shows the `ClusterVersion` CR to trigger the update. The `channel`, `upstream`, and `desiredVersion` fields are all required for image pre-caching.
+
The `PolicyGenTemplate` CR generates two policies:

`du-upgrade-platform-upgrade-prep`:: This policy does the preparation work for the platform update. It creates the `ConfigMap` CR for the desired release image signature, creates the image content source of the mirrored release image repository, and updates the cluster version with the desired update channel and the update graph reachable by the spoke cluster in the disconnected environment.

`du-upgrade-platform-upgrade`:: This is the policy used to perform platform upgrade.

.. Add the `du-upgrade.yaml` to the `kustomization.yaml` located in the ZTP git repository for the `PolicyGenTemplate` CRs and push the changes to the git repository.
+
ArgoCD pulls the changes from the git repository and generates the policies on the Hub cluster.

.. Check the created policies by running the following command:
+
[source,terminal]
----
$ oc get policies -A | grep platform-upgrade
----

. Apply the required update resources before starting the platform update with TALO.

.. Save the content of the `platform-upgrade-prep` `ClusterUpgradeGroup` CR with the `du-upgrade-platform-upgrade-prep` policy and the target spoke clusters to the `cgu-platform-upgrade-prep.yml` file.
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-platform-upgrade-prep
  namespace: default
spec:
  managedPolicies:
  - du-upgrade-platform-upgrade-prep
  clusters:
  - spoke1
  remediationStrategy:
    maxConcurrency: 1
  enable: true
----

.. Apply the policy to the Hub cluster by running the following command:
+
[source,terminal]
----
$ oc apply -f cgu-platform-upgrade-prep.yml
----

.. Monitor the update process and wait for completion. Then ensure that the policy becomes compliant by running the following command:
+
[source,terminal]
----
$ oc get policies --all-namespaces
----

. Pre-cache the images for the platform update.
.. Save the content of the platform update `ClusterGroupUpgrade` CR with the `du-upgrade-platform-upgrade` policy and the target clusters to the `cgu-platform-upgrade.yml` file. This `ClusterGroupUpgrade` CR is configured to only perform the pre-caching job without the actual cluster update.
+
[source,yaml]
----
apiVersion: ran.openshift.io/v1alpha1
kind: ClusterGroupUpgrade
metadata:
  name: cgu-platform-upgrade
  namespace: default
spec:
  managedPolicies:
  - du-upgrade-platform-upgrade
  preCaching: true
  clusters:
  - spoke1
  remediationStrategy:
    maxConcurrency: 1
  enable: false
----

.. Apply the CR to the Hub cluster by running the following command:
+
[source,terminal]
----
$ oc apply -f cgu-platform-upgrade-prep.yml
----

.. Monitor the date process and wait for the pre-caching to complete. Check the status of pre-caching by running the following command on the spoke cluster:
+
[source,terminal]
----
$ oc get jobs,pods -n openshift-talo-pre-cache
----

. Start platform update.
.. To start the update, enable the `cgu-platform-upgrade` and disable pre-caching by running the following command:
+
[source,terminal]
----
oc --namespace=default patch clustergroupupgrade.ran.openshift.io/cgu-platform-upgrade \
--patch '{"spec":{"enable":true, "preCaching": false}}' --type=merge
----

.. Monitor the process and wait for completion. Then ensure that the policy becomes compliant by running the following command:
+
[source,terminal]
----
$ oc get policies --all-namespaces
----