// Module included in the following assemblies:
// Epic TELCOSTRAT-160 (4.15/4.16), story TELCODOCS-1576
// * scalability_and_performance/ztp-talm-updating-managed-policies.adoc

:_mod-docs-content-type: PROCEDURE
[id="ztp-image-based-upgrade-prep_{context}"]
= Preparing the {sno} cluster for the image-based upgrade

When you deploy the {lcao} on a cluster, a blank `ImageBasedUpgrade` CR is automatically created.
You use this CR to specify the image repository of the seed image and to move through the different stages.

.Prerequisites

* You installed {lcao}.
* You generated a seed image from a compatible seed cluster.
* You installed the OADP Operator.
* You have an S3-compatible storage solution and a ready-to-use bucket created with proper credentials configured.

// are there other prereqs?

.Procedure

This example procedure demonstrates how to back up and upgrade a cluster with applications on a persistent volume.

[NOTE]
====
The target cluster does not need to be detached from the hub cluster.
====

. (Optional) Create your OADP `Backup` and `Restore` CRs. For more information, see _"Additonal resources"_.

.. Define the restore order for the OADP Operator in the `Restore` CR by using the `lca.openshift.io/apply-wave` field:
+
[source,yaml]
----
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: acm-klusterlet
  namespace: openshift-adp
  labels:
    velero.io/storage-location: default
  annotations:
    lca.openshift.io/apply-wave: "1"
spec:
  backupName:
    acm-klusterlet
---
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: example-app
  namespace: openshift-adp
  labels:
    velero.io/storage-location: default
  annotations:
    lca.openshift.io/apply-wave: "3"
spec:
  backupName:
    example-app
---
apiVersion: velero.io/v1
kind: Restore
metadata:
  name: localvolume
  namespace: openshift-adp
  labels:
    velero.io/storage-location: default
  annotations:
    lca.openshift.io/apply-wave: "2"
spec:
  backupName:
    localvolume
----

.. Create a `kustomization.yaml` that will append the information to a new `ConfigMap` CR:
+
[source,yaml]
----
configMapGenerator:
- name: oadp-cm
  namespace: openshift-adp
  files:
  - backup_acm_klusterlet.yaml
  - backup_localvolume.yaml
  - backup_app.yaml
  - restore_acm_klusterlet.yaml
  - restore_localvolumes.yaml
  - restore_app.yaml
----

.. Create the `ConfigMap` CR:
+
[source,terminal]
----
$ kustomize build ./ -o OadpCm.yaml
----
+
.Example output
+
[source,terminal]
----
kind: ConfigMap
metadata:
  name: oadp-cm-example
  namespace: openshift-adp
[...]
----

.. Apply the `ConfigMap` CR:
+
[source,terminal]
----
$ oc apply -f OadpCm.yaml
----

. Apply the the `ImageBasedUpgrade` CR:
+
[source,yaml]
----
apiVersion: lca.openshift.io/v1alpha1
kind: ImageBasedUpgrade
metadata:
  name: example-upgrade
spec:
  stage: Idle
  seedImageRef:
    version: 4.14.6 <1>
    image: <seed_container_image> <2>
#  oadpContent: <3>
#  - name: oadp-cm-example
#    namespace: openshift-adp
----
<1> Specify the platform version on the seed image.
<2> Specify the repository where the target cluster can pull the seed image from.
<3> (Optional) Add the `oadpContent` section with the OADP `ConfigMap` information.
// For telco, we need a sample with extraManifests and oadpContent

. Move the stage to `Prep` in the `ImageBasedUpgrade` CR:
+
[source,terminal]
----
$ oc patch imagebasedupgrades.lca.openshift.io upgrade -p='{"spec": {"stage": "Prep"}}' --type=merge -n openshift-lifecycle-agent
----

+
The {lcao} checks for the health of the cluster and pulls the seed image to the target cluster.
Then, the Operator precaches all the required images on the target cluster.

// What else, if anything?

.Verification

. Check the status of the `ImageBasedUpgrade` CR.
+
[source,terminal]
----
$ oc get ibu -A -oyaml
----

+
.Example output
[source,yaml]
----
status:
  conditions:
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: In progress
    observedGeneration: 2
    reason: InProgress
    status: "False"
    type: Idle
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: 'Prep completed: total: 121 (pulled: 1, skipped: 120, failed: 0)'
    observedGeneration: 2
    reason: Completed
    status: "True"
    type: PrepCompleted
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: Prep completed
    observedGeneration: 2
    reason: Completed
    status: "False"
    type: PrepInProgress
  observedGeneration: 2
----

// Troubleshooting?