// Module included in the following assemblies:
// Epic TELCOSTRAT-160 (4.15/4.16), story TELCODOCS-1576
// * scalability_and_performance/ztp-talm-updating-managed-policies.adoc

:_mod-docs-content-type: PROCEDURE
[id="ztp-image-based-upgrade-rollback_{context}"]
= (Optional) Initiating rollback of the {sno} cluster after an image-based upgrade

In case the upgrade fails, an automatic rollback is initiated.
You can also manually roll back if you encounter unresolvable issues after an upgrade.

.Prerequisites

* You installed the OpenShift CLI (`oc`).

* You logged in to the hub cluster as a user with `cluster-admin` privileges.

// are there other prereqs?

.Procedure

. Move to the rollback stage by changing the `Upgrade` value to `Rollback` in the `ImageBasedUpgrade` CR.
+
[source,yaml]
----
apiVersion: lca.openshift.io/v1alpha1
kind: ImageBasedUpgrade
metadata:
  name: example-upgrade
spec:
  stage: Rollback
  seedImageRef:
    version: 4.14.6
    image: <seed_container_image>
----
// For telco, we need a sample with extraManifests and oadpContent

. Move to the rollback stage by changing the `Upgrade` value to `Rollback` in the `ImageBasedUpgrade` CR.
+
[source,terminal]
----
$ oc patch imagebasedupgrades.lca.openshift.io upgrade -p='{"spec": {"stage": "Rollback"}}' --type=merge
----


. The {lcao} reboots the cluster with the previously installed version of {product-title}.

. Commit to the rollback by changing the `Rollback` value to `Idle` in the `ImageBasedUpgrade` CR:
+
[source,terminal]
----
$ oc patch imagebasedupgrades.lca.openshift.io upgrade -p='{"spec": {"stage": "Idle"}}' --type=merge -n openshift-lifecycle-agent
----

// Verification/Troubleshooting?