// Module included in the following assemblies:
// Epic TELCOSTRAT-160 (4.15/4.16), story TELCODOCS-1576
// * scalability_and_performance/ztp-talm-updating-managed-policies.adoc

:_mod-docs-content-type: PROCEDURE
[id="ztp-image-based-upgrading-with-backup_{context}"]
= Upgrading the {sno} cluster with {lcao}

When you generated the seed image and completed the `Prep` stage, you can begin upgrading the target clusters.
During the upgrade process, the OADP Operator creates a backup of the artifacts specified in the OADP CRs, then {lcao} reimages the cluster.

[IMPORTANT]
====
If the upgrade fails or stops, an automatic rollback is initiated.
You can initiate a manual rollback, in case you encounter an issue after the upgrade.
For more information on manual rollback, see "(Optional) Initiating rollback of the {sno} clusters after an image-based upgrade".
====

.Prerequisites

* You generated a seed image for the target cluster.
* You have completed the `Prep` stage.

.Procedure

. Move to the upgrade stage by changing the `Prep` value to `Upgrade` in the `ImageBasedUpgrade` CR.
+
[source,terminal]
----
$ oc patch imagebasedupgrades.lca.openshift.io upgrade -p='{"spec": {"stage": "Upgrade"}}' --type=merge
----

. Check the status of the `imageBasedUpgrade` CR:
+
[source,terminal]
----
$ oc get imagebasedupgrades.lca.openshift.io upgrade -oyaml
----

+
.Example output
[source,yaml]
----
status:
  conditions:
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: In progress
    observedGeneration: 2
    reason: InProgress
    status: "False"
    type: Idle
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: 'Prep completed: total: 121 (pulled: 1, skipped: 120, failed: 0)'
    observedGeneration: 2
    reason: Completed
    status: "True"
    type: PrepCompleted
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: Prep completed
    observedGeneration: 2
    reason: Completed
    status: "False"
    type: PrepInProgress
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: Upgrade completed
    observedGeneration: 3
    reason: Completed
    status: "True"
    type: UpgradeCompleted
----

. The OADP Operator creates a backup of the data specified in the OADP `Backup` and `Restore` CRs.

. The target cluster reboots.

. Monitor the status of the CR:
+
[source,terminal]
----
$ oc get ibu -A -oyaml
----
//check the proper short command for IBU CR monitoring

. The cluster reboots.

After the cluster reboots, the {lcao} does the following:
* Regenerates the certificates
* Restores platform cluster configuration to their original values
* Applies site configuration that cannot be done during seed generation because it is unique to each cluster
* Restores the application

[NOTE]
====
When you commit to the rollback by setting the stage to `Idle`, all the resources created by the {lcao} is deleted.
====

.Verification

. Check the status of the `imageBasedUpgrade` CR:
+
[source,terminal]
----
$ oc get imagebasedupgrades.lca.openshift.io upgrade -oyaml
----

+
.Example output
[source,yaml]
----
status:
  conditions:
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: In progress
    observedGeneration: 2
    reason: InProgress
    status: "False"
    type: Idle
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: 'Prep completed: total: 121 (pulled: 1, skipped: 120, failed: 0)'
    observedGeneration: 2
    reason: Completed
    status: "True"
    type: PrepCompleted
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: Prep completed
    observedGeneration: 2
    reason: Completed
    status: "False"
    type: PrepInProgress
  - lastTransitionTime: "2024-01-01T09:00:00Z"
    message: Upgrade completed
    observedGeneration: 3
    reason: Completed
    status: "True"
    type: UpgradeCompleted
----

. Check the status of the cluster restoration:
+
[source,terminal]
----
$ oc get restores -n openshift-adp -o custom-columns=NAME:.metadata.name,Status:.status.phase,Reason:.status.failureReason
----

+
[source,terminal]
----
NAME             Status      Reason
acm-klusterlet   Completed   <none>
apache-app       Completed   <none>
localvolume      Completed   <none>
----