:_mod-docs-content-type: ASSEMBLY
[id="ibi-image-based-install_{context}"]
<<<<<<< HEAD
= About image-based installations for {sno} clusters
=======
= About an image-based installation for {sno} clusters
>>>>>>> 48d0c841bb (TELCODOCS-1887: Adding section for IBI workflow)
include::_attributes/common-attributes.adoc[]
:context: ibi-factory-image-based-install

toc::[]

<<<<<<< HEAD
Use the `openshift-install` installation program to create a live installation ISO for preinstalling {sno} on bare-metal hosts. For more information about downloading the installation program, see _"Installation process"_ in the _"Additional resources"_ section.

The installation program takes a seed image URL and other inputs, such as the release version of the seed image and the disk to use for the installation process, and creates a live installation ISO. You can then start the host using the live installation ISO to begin preinstallation. When preinstallation is complete, the host is ready to ship to a remote site for the final site-specific configuration and deployment.

The following are the high-level steps to preinstall a {sno} cluster using an image-based installation:
=======
Use the `openshift-install` installation program to create a live installation ISO for preinstalling {sno} on bare-metal hosts. For more information about downloading the installation program, see _Installation process_ in the _Additional resources_ section.

The installation program takes a seed image URL and other inputs, such as the release version of the seed image and the disk to use for the installation process, and creates a live installation ISO that references these installation artifacts. You can then start the host using the live installation ISO to begin the preinstallation of the host. When the preinstallation is complete, the host is ready to ship to a remote site for the final site-specific configuration and deployment.

The following are the high-level steps to preinstall a {sno} cluster to a host using an image-based installation:
>>>>>>> 48d0c841bb (TELCODOCS-1887: Adding section for IBI workflow)

* Generate a seed image.
* Create a live installation ISO using the installation program.
* Start the host using the live installation ISO to preinstall the host.

include::modules/ibi-create-iso-for-bmh.adoc[leveloffset=+1]

include::modules/ibi-provision-install-iso-to-bmh.adoc[leveloffset=+1]

include::modules/ibi-installer-installation-config.adoc[leveloffset=+1]

[role="_additional-resources"]
== Additional resources

* xref:../../installing/overview/index.adoc#installation-process_ocp-installation-overview[Installation process]
